### ISSUE TITLE
cmd/keylight: build out CLI application

### ISSUE THREAD

**Issue by mdlayher** [mdlayher/keylight#2]
The CLI should support operations such as adjusting brightness, temperature, etc. rather than just toggling on/off.

**Comment by mvdan** [comment]
It seems like some of this is now implemented, e.g. I can use `-b` to set the absolute brightness percentage.

Would you be up for adding more features there? For example, I want to have three keyboard shortcuts: toggle light, increase brightness, decrease brightness. The first of the three can be done via just `keylight`, but the other two would require some shell glue code to obtain the current brightness via `keylight -i`, do math, then `keylight -b`.

How about supporting `keylight -d +5%` and `keylight -d -5%` as a way to add/subtract relative percentages? I realise that the minus sign is a bit awkward given the flag parsing, but I still think it would work. If the addition or subtraction leave us above the maximum or below the minimum percentage, we'd just use the maximum or minimum.

**Comment by mvdan** [comment]
Also, it took me a while to understand that "no flags" means "toggle light", as it's not documented in `keylight -h` :)

**Comment by mdlayher** [comment]
Sounds great, PRs welcome! I didn't realize anyone but me was actually using this tool.

**Comment by mvdan** [comment]
I think I saw it from a tweet by @stapelberg a long time ago, and remembered it recently when I was annoyed by the app :)

**Comment by mdlayher** [comment]
Pretty sure this is done!
